name       : cool-retro-term
version    : 1.0.0
release    : 1
source     :
    - git|https://github.com/Swordfish90/cool-retro-term : v1.0.0
license    :
    - GPL-2.0
    - GPL-3.0
component  : desktop
summary    : cool-retro-term is a terminal emulator which mimics the look and feel of the old cathode tube screens
description: |
    cool-retro-term is a terminal emulator which mimics the look and feel of the old cathode tube screens
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
setup      : |
    qmake
build      : |
    %make
install    : |
    install -D -m 00644 cool-retro-term.desktop $installdir/usr/share/applications/cool-retro-term.desktop
    install -D -m 00755 qmltermwidget/QMLTermWidget/libqmltermwidget.so $installdir/usr/lib/qt5/qml/QMLTermWidget/libqmltermwidget.so
    cp -R qmltermwidget/src/qmldir $installdir/usr/lib/qt5/qml/QMLTermWidget/
    install -D -m 00644 qmltermwidget/src/QMLTermScrollbar.qml $installdir/usr/lib/qt5/qml/QMLTermWidget/QMLTermScrollbar.qml
    cp -R qmltermwidget/lib/kb-layouts $installdir/usr/lib/qt5/qml/QMLTermWidget/
    cp -R qmltermwidget/lib/color-schemes $installdir/usr/lib/qt5/qml/QMLTermWidget/
    install -D -m 00755 cool-retro-term $installdir/usr/bin/cool-retro-term
    install -D -m 00644 app/icons/32x32/cool-retro-term.png $installdir/usr/share/icons/hicolor/32x32/apps/cool-retro-term.png
    install -D -m 00644 app/icons/64x64/cool-retro-term.png $installdir/usr/share/icons/hicolor/64x64/apps/cool-retro-term.png
    install -D -m 00644 app/icons/128x128/cool-retro-term.png $installdir/usr/share/icons/hicolor/128x128/apps/cool-retro-term.png
    install -D -m 00644 app/icons/256x256/cool-retro-term.png $installdir/usr/share/icons/hicolor/256x256/apps/cool-retro-term.png
