name       : cool-retro-term
version    : 1.1.0
release    : 4
source     :
    - https://github.com/Swordfish90/cool-retro-term/archive/1.1.0.tar.gz : f5734aefdfc2e9343b6a24ee297f543a36a2e0df0da0f9ac94b00d9300185f8a
    - https://github.com/Swordfish90/qmltermwidget/archive/0.2.0.tar.gz : 23e19eedb59d6fe3e37ecc06872f54befd94384946926e009c42c4b39914cfe2
license    :
    - GPL-2.0-or-later
    - GPL-3.0-or-later
component  : desktop
summary    : cool-retro-term is a terminal emulator which mimics the look and feel
    of the old cathode tube screens
description: |
    cool-retro-term is a terminal emulator which mimics the look and feel of the old cathode tube screens
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
rundeps    :
    - qt5-graphicaleffects
    - qt5-quickcontrols
setup      : |
    tar xf $sources/0.2.0.tar.gz -C $workdir/qmltermwidget --strip-components=1
    %qmake
build      : |
    %make
install    : |
    install -D -m 00644 cool-retro-term.desktop $installdir/usr/share/applications/cool-retro-term.desktop
    install -D -m 00755 qmltermwidget/QMLTermWidget/libqmltermwidget.so $installdir/usr/lib64/qt5/qml/QMLTermWidget/libqmltermwidget.so
    cp -R qmltermwidget/src/qmldir $installdir/usr/lib64/qt5/qml/QMLTermWidget/
    install -D -m 00644 qmltermwidget/src/QMLTermScrollbar.qml $installdir/usr/lib64/qt5/qml/QMLTermWidget/QMLTermScrollbar.qml
    cp -R qmltermwidget/lib/kb-layouts $installdir/usr/lib64/qt5/qml/QMLTermWidget/
    cp -R qmltermwidget/lib/color-schemes $installdir/usr/lib64/qt5/qml/QMLTermWidget/
    install -D -m 00755 cool-retro-term $installdir/usr/bin/cool-retro-term
    install -D -m 00644 app/icons/32x32/cool-retro-term.png $installdir/usr/share/icons/hicolor/32x32/apps/cool-retro-term.png
    install -D -m 00644 app/icons/64x64/cool-retro-term.png $installdir/usr/share/icons/hicolor/64x64/apps/cool-retro-term.png
    install -D -m 00644 app/icons/128x128/cool-retro-term.png $installdir/usr/share/icons/hicolor/128x128/apps/cool-retro-term.png
    install -D -m 00644 app/icons/256x256/cool-retro-term.png $installdir/usr/share/icons/hicolor/256x256/apps/cool-retro-term.png
